USE [master]
GO
/****** Object:  Database [DBGustov]    Script Date: 27/12/2023 14:17:29 ******/
CREATE DATABASE [DBGustov]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBGustov', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBGustov.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBGustov_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBGustov_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DBGustov] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBGustov].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBGustov] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBGustov] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBGustov] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBGustov] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBGustov] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBGustov] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBGustov] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBGustov] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBGustov] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBGustov] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBGustov] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBGustov] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBGustov] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBGustov] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBGustov] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DBGustov] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBGustov] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBGustov] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBGustov] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBGustov] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBGustov] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBGustov] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBGustov] SET RECOVERY FULL 
GO
ALTER DATABASE [DBGustov] SET  MULTI_USER 
GO
ALTER DATABASE [DBGustov] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBGustov] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBGustov] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBGustov] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBGustov] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBGustov] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DBGustov', N'ON'
GO
ALTER DATABASE [DBGustov] SET QUERY_STORE = OFF
GO
USE [DBGustov]
GO
/****** Object:  Table [dbo].[Cargo]    Script Date: 27/12/2023 14:17:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cargo](
	[IdCargo] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](150) NULL,
	[Estado] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Departamento]    Script Date: 27/12/2023 14:17:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Departamento](
	[IdDepartamento] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](150) NULL,
	[Estado] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdDepartamento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Empleado]    Script Date: 27/12/2023 14:17:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Empleado](
	[IdEmpleado] [int] IDENTITY(1,1) NOT NULL,
	[NombreCompleto] [varchar](150) NULL,
	[IdDepartamento] [int] NULL,
	[IdCargo] [int] NULL,
	[sueldo] [int] NULL,
	[Estado] [varchar](50) NULL,
	[FechaContrato] [datetime] NULL,
	[FechaCreacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEmpleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vacacion]    Script Date: 27/12/2023 14:17:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vacacion](
	[IdVacaciones] [int] IDENTITY(1,1) NOT NULL,
	[Detalle] [varchar](150) NULL,
	[IdEmpleado] [int] NULL,
	[FechaInicio] [datetime] NULL,
	[FechaFin] [datetime] NULL,
	[Estado] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[Gestion] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdVacaciones] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cargo] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Departamento] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Empleado] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Vacacion] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Empleado]  WITH CHECK ADD FOREIGN KEY([IdCargo])
REFERENCES [dbo].[Cargo] ([IdCargo])
GO
ALTER TABLE [dbo].[Empleado]  WITH CHECK ADD FOREIGN KEY([IdDepartamento])
REFERENCES [dbo].[Departamento] ([IdDepartamento])
GO
ALTER TABLE [dbo].[Vacacion]  WITH CHECK ADD FOREIGN KEY([IdEmpleado])
REFERENCES [dbo].[Empleado] ([IdEmpleado])
GO
USE [master]
GO
ALTER DATABASE [DBGustov] SET  READ_WRITE 
GO
